<<<<<<< HEAD
[tool.poetry]
name = "backend"
package-mode = false
version = "0.1.0"
description = "BaseGraphQlFastApi"
authors = ["DeveloperInal <166642110+DeveloperInal@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.2"
pydantic-settings = "^2.5.2"
pydantic = {extras = ["email"], version = "^2.9.2"}
uvicorn = "^0.31.1"
loguru = "^0.7.2"
jinja2 = "^3.1.4"
bcrypt = "^4.2.0"
strawberry-graphql = { version = "^0.259.0", python = ">=3.13,<4.0" }
sqlalchemy = "^2.0.38"
asyncpg = "^0.30.0"
alembic = "^1.14.1"
black = "^25.1.0"
pyjwt = "^2.10.1"
cryptography = "^44.0.1"
aiofiles = "^24.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
=======
[tool.poetry]
name = "backend"
package-mode = false
version = "0.1.0"
description = "BaseGraphQlFastApi"
authors = ["DeveloperInal <166642110+DeveloperInal@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.2"
pydantic-settings = "^2.5.2"
pydantic = {extras = ["email"], version = "^2.9.2"}
uvicorn = "^0.31.1"
loguru = "^0.7.2"
jinja2 = "^3.1.4"
bcrypt = "^4.2.0"
strawberry-graphql = { version = "^0.259.0", python = ">=3.13,<4.0" }
sqlalchemy = "^2.0.38"
asyncpg = "^0.30.0"
alembic = "^1.14.1"
black = "^25.1.0"
pyjwt = "^2.10.1"
cryptography = "^44.0.1"
aiofiles = "^24.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
>>>>>>> d8a3317a0a70d13af2213931a89ea36727542756
